version: "3.9"

services:
  document-server:
    container_name: document-server
    image: onlyoffice/documentserver-de:latest
    expose:
      - "80"
    environment:
      - ALLOW_META_IP_ADDRESS=true
    volumes:
      - ./app/onlyoffice/documentserver/data:/var/www/onlyoffice/Data
      - ./app/onlyoffice/documentserver/logs:/var/log/onlyoffice
      - ./app/onlyoffice/documentserver/lib:/var/lib/onlyoffice
      - ./app/onlyoffice/documentserver/db:/var/lib/postgresql
    env_file:
      - .env


  example:
    container_name: python-example
    build:
      context: .
    expose:
      - "80"
    environment:
      - ADDRESS=0.0.0.0
      - DOCUMENT_SERVER_PRIVATE_URL=http://proxy:8080
      - DOCUMENT_SERVER_PUBLIC_URL=http://localhost:8080
      - EXAMPLE_URL=http://proxy
      - PORT=80
    env_file:
      - .env


  proxy:
    container_name: proxy
    build:
      context: .
      target: proxy
    ports:
      - "80:80"
      - "8080:8080"

